name: IAST demo using Contrast
on: push

jobs:
 Build: 
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
    
