name: IAST demo using Contrast!!
on: push

jobs:
 IAST_Security: 
    #runs-on: Linux
    runs-on: ubuntu-latest 
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17
          architecture: x64
      - uses: actions/checkout@v3
      - name: Building the application
        run: |
           #cd /home/sneha/Downloads/actions-runner/_work/WebGoat-IAST-Demo/WebGoat-IAST-Demo
           pwd
           ./mvnw clean install
      
      - name: Install contrast agent
        run: |
           pwd
           #cd /home/sneha/Desktop/
           #curl -L 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.contrastsecurity&a=contrast-agent&v=LATEST' -o contrast.jar
           
      - name: Running and enable Contrast to monitor the appication
        run: |
           #java -javaagent:/home/sneha/Desktop/contrast.jar -jar /home/sneha/Downloads/actions-runner/_work/WebGoat-IAST-Demo/WebGoat-IAST-Demo/target/webgoat-2023.3.jar
           ls
           pwd
           sudo cp ~/webgoat-2023.3.jar contrast
           sudo cd contrast
           ls
           sudo java -javaagent: contrast.jar -jar webgoat-2023.3.jar
